### ISSUE TITLE
Shouldn't it refer to zidev.ieee instead of dev.ieee to avoid get 'ReferenceError: dev is not defined' ?

### ISSUE THREAD

**Issue by lsteelandt** [nouknouk/node-zigate#4]
https://github.com/nouknouk/node-zigate/blob/9eef0bc1e8a13d315820f0a6cef535e30e68dab8/src/coordinator/coordinator.js#L417

When the Hardware Zigate hold a device not 'known' by the coordinator object (software Zigate), the calling **`coordinator.queryDevices()`** thrown an **`ReferenceError: dev is not defined`**.

I suggest that is coming from the reference of **`dev.ieee`** instead of **`zidev.ieee`**. 
Am I right ?

**Comment by nouknouk** [comment]
You're right, there was a typo.

It has been fixed in branch dev/3.1a: https://github.com/nouknouk/node-zigate/commit/b8c2e05f9ad509b1bd1b7f54fa3d9280bd87c604

will be merged with the rest in the master branch soon.
